package main.java;

public enum AdditionalInfo {
    HASATTIC,
    HASBARBECUEAREA,
    HASBASEMENT,
    HASCEILINGFAN,
    HASDECK,
    HASDOCK,
    HASDOORMAN,
    HASDOUBLEPANEWINDOWS,
    HASELEVATOR,
    HASLAWN,
    HASPATIO,
    HASPOND,
    HASPOOL,
    HASPORCH,
    HASSAUNA,
    HASSECURITYSYSTEM,
    HASWETBAR,
    HASFIREPLACE,
    HASGARDEN,
    HASGATEDENTRY,
    HASHOTTUBSPA
}
