package main.java;
public enum Style {
    AGRICULTURAL,
    CONDOMINIUM,
    COOPERATIVE,
    DETACHED,
    DUPLEX,
    FREEHOLD,
    MULTIFAMILY,
    MULTIGENERATIONAL,
    NEWCONSTRUCTION,
    RECREATIONAL,
    VACATION,
    SEMIDETACHED,
    STACKEDTOWNHOUSE
}
